---
title: "Fusión de los datos"
author: "Luis Cobiella Hernández"
date: "9/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preprocesado
Descarga de datos y metados y carga de funciones de preprocesado.
```{r preprocess, results="hide", message=FALSE}
source("preprocess.R")
```

# Fusión de tablas para predecir la duración de la estancia
Para evitar saturar los recursos del sistema se aplica además la función de reducción, con esto filtramos solo las localizaciones de nivel NUTS 0, es decir, los países al completo, ignorando sus regiones.

```{r merge_length_stay}
# length_stay -------------------------------------------------------------
staff_all <- get_staff_all()
staff_hosp <- get_staff_hosp()

staff_all_merge <- staff_all %>%
  filter(unit=="P_HTHAB") %>%
  select(-c(unit, metadata)) %>%
  mutate(hosp=FALSE) %>%
  rename(num_prof=value)

staff_hosp_merge <- staff_hosp %>%
  mutate(hosp=TRUE) %>%
  select(-metadata) %>%
  rename(num_prof=value)

staff <- bind_rows(staff_all_merge, staff_hosp_merge)

length_stay <- get_length_stay(sex=TRUE) %>% reduce_data(icd10=NULL)

length_stay_merge <- length_stay %>%
  select(-c(indic_he, unit, metadata)) %>%
  rename(length_stay=value)

print(head(staff))
print(head(length_stay_merge))

length_full <- right_join(staff, length_stay_merge)

print(head(length_full))
print(summary(length_full))
print(object.size(length_full), units="auto")
```