FROM ghcr.io/rocker-org/tidyverse:4.3.1

RUN git clone https://github.com/jueves/eurostat_health.git

RUN mv /eurostat_health /home/rstudio

RUN chown rstudio:rstudio -R /home/rstudio/eurostat_health

#COPY install_packages.R /home/rstudio/

#RUN Rscript /home/rstudio/install_packages.R
