FROM docker.io/rocker/cuda:4.3.2

RUN git clone https://github.com/jueves/eurostat_health.git

RUN mv /eurostat_health /home/rstudio

RUN chown rstudio:rstudio -R /home/rstudio/eurostat_health

COPY docker_src/install_packages.R /home/rstudio/

RUN Rscript /home/rstudio/install_packages.R
