FROM ghcr.io/rocker-org/tidyverse:4.3.1

RUN apt-get update && apt-get install -y  --no-install-recommends python3-pip python3-venv

RUN pip3 install requests pandas numpy

RUN R -q -e 'install.packages(c("reticulate", "plotly"))'
